//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA.APPID.BookService.Interceptor.ErrorCodes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA.APPID.BookService.Interceptor.ErrorCodes.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A System Exception Occured,Critical,System.
        /// </summary>
        internal static string APP00000 {
            get {
                return ResourceManager.GetString("APP00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty/Invalid Request parameters, Error, Application.
        /// </summary>
        internal static string APP00100 {
            get {
                return ResourceManager.GetString("APP00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A System exception occured during Database call, Critical, System.
        /// </summary>
        internal static string APP00400 {
            get {
                return ResourceManager.GetString("APP00400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found in Database, Error, Application.
        /// </summary>
        internal static string APP00401 {
            get {
                return ResourceManager.GetString("APP00401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A System Exception Occured during Service call, Critical, System.
        /// </summary>
        internal static string APP00700 {
            get {
                return ResourceManager.GetString("APP00700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault returned from extrenal service, Error, Application.
        /// </summary>
        internal static string APP00701 {
            get {
                return ResourceManager.GetString("APP00701", resourceCulture);
            }
        }
    }
}
